<br /># Dockerfile api
FROM node:8.11.1
RUN useradd --user-group --create-home --shell /bin/false app &&\
  npm install --global npm &&\
  npm install --global nodemon &&\
  npm install --global express

ENV HOME=/home/app

COPY package.json npm-shrinkwrap.json $HOME/library/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/library
RUN npm cache clean && npm install --silent --progress=false

USER root
COPY . $HOME/library
RUN chown -R app:app $HOME/*
USER app

CMD ["npm", "start"]